### ISSUE TITLE
Cant get motionbuilder 2019/2018 to work with Meshsync

### ISSUE THREAD

**Issue by Hermanator123** [Unity-Technologies/MeshSyncDCCPlugin#107]
Hi Unity.
Im trying out Meshsync, creating an AR application with normcore sdk and meshsync.
It works great with blender but I need it to work with Motionbuilder .

Im having issues not being able to connect motionbuilder to Unity.
Plugin is offline in motionbuilder see picture1.
The motiobuilder plugin is not showing up in unity Preferences.

Any ideas how to fix?
![Meshsync1](https://user-images.githubusercontent.com/37322452/116204098-b1ee6880-a73c-11eb-82a5-113a32b6e810.jpg)
![Meshsync2](https://user-images.githubusercontent.com/37322452/116204104-b450c280-a73c-11eb-806b-f99e65bc6842.JPG)

Best regards
Herman

**Comment by sindharta** [comment]
> The motiobuilder plugin is not showing up in unity Preferences.

MeshSync doesn't support automatic plugin installation for MotionBuilder yet, so yes, it won't appear in Unity Preferences

> Plugin is offline in motionbuilder see picture1.

If you meant the red color on the Online menu item. Please disregard it, and try syncing your objects to MeshSync by clicking Manual Sync (or checking Auto Sync checkbox).
Please let me know how it goes.

**Comment by sindharta** [comment]
Closing due to non-activity.
Please feel free to reopen if necessary.
