### ISSUE TITLE
Motion Builder not detected automatically and manual add not possible

### ISSUE THREAD

**Issue by judasbenhur** [Unity-Technologies/MeshSyncDCCPlugin#120]
In preview version 0.8.0 both my 2019 and 2020 Motion Builder installations are not auto-detected. Trying to manually add them by pointing to the folder containing the installation or binary files of Motion Builder brings up a error message that says no DCC detected.

**Comment by sindharta** [comment]
Automatic plugin installation doesn't support MotionBuilder yet ([MeshSync docs](https://docs.unity3d.com/Packages/com.unity.meshsync@0.8/manual/en/Preferences.html)).

Unfortunately, you will have to do [manual installation](https://github.com/Unity-Technologies/MeshSyncDCCPlugins/blob/dev/Documentation~/en/Installation.md) for this at the moment.

Please create on issue on the [MeshSync github page](https://github.com/unity3d-jp/MeshSync) to request this feature.

**Comment by judasbenhur** [comment]
got it. Thank you!
