### ISSUE TITLE
The address line con't be modify correctly in  Motionbuilder!

### ISSUE THREAD

**Issue by Bn-com** [Unity-Technologies/MeshSyncDCCPlugin#122]
I want to change the IP address, but there are some weird things happening. The address cannot be typed correctly.  in  Motion builder 2018..  
like this..
i type "192.168.2.1",   but, when I' pushing the Enter Key, the address shows "192.168 ", it doesn't show the full contents that i typed.

Please~~ Help...  !!!

**Comment by sindharta** [comment]
What is your platform ? (Windows, Linux ?)
And can you post a video or an animated gif showing this issue ?

**Comment by sindharta** [comment]
Closing because 

1. We can't reproduce the issue
2. There is no response

Please feel free to reopen if necessary
