### ISSUE TITLE
Can't find poco - building plugin for Maya 2022

### ISSUE THREAD

**Issue by LuLebon** [Unity-Technologies/MeshSyncDCCPlugin#134]
Hi,

I'm trying to build MeshSyncDCC plugin for Maya 2022 on windows but i'm blocked at this command line :
> make_meshsync_dcc_plugin.bat MeshSync-0.9.0-preview -DBUILD_MAYA_2022_PLUGIN=ON

It gives me the following message :

> -- Selecting Windows SDK version 10.0.16299.0 to target Windows 10.0.19042.
>	-- The C compiler identification is MSVC 19.13.26128.0
>	-- The CXX compiler identification is MSVC 19.13.26128.0
>	-- Detecting C compiler ABI info
>	-- Detecting C compiler ABI info - done
>	-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe - skipped
>	-- Detecting C compile features
>	-- Detecting C compile features - done
>	-- Detecting CXX compiler ABI info
>	-- Detecting CXX compiler ABI info - done
>	-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe - skipped
>	-- Detecting CXX compile features
>	-- Detecting CXX compile features - done
>	Unity Package Version: 0.9.0-preview
>	-- Looking for Poco install directory structure.
>	-- Poco: Could not find Poco install directory
>	Downloading MeshSync MeshSync-0.9.0-preview
>	-- [download 100% complete]
>	-- [download 0% complete]
>	CMake Error at Build/cmake_modules/Utilities.cmake:18 (message):
>	  Could not download MeshSync MeshSync-0.9.0-preview !
>	Call Stack (most recent call first):
>	  Build/cmake_modules/MeshSync.cmake:12 (download_and_extract)
>	  CMakeLists.txt:78 (get_meshsync)
>
>	-- Configuring incomplete, errors occurred!

Apparently, it can't find poco, even if Poco_DIR is in my path.

If you have any idea what I might have done wrong, that would be very helpfull. I have been stuck on this for a long time.

Thanks a lot

**Comment by sindharta** [comment]
Have you built Poco ?
Please refer to the [building plugins](https://github.com/Unity-Technologies/MeshSyncDCCPlugins/blob/dev/Plugins~/Docs/en/BuildDCCPlugins.md#building-on-windows) page

**Comment by LuLebon** [comment]
Thanks for the quick answer. 

I built poco without any error message. I have some warning but they were about variables type changes and a command line without argument ( poco kept building after those warnings).

**Comment by sindharta** [comment]
>  I have some warning but they were about variables type changes and a command line without argument 

It seems that it's safe to ignore those warnings then ?
How did it go ? Did you manage to build the plugin ?

**Comment by LuLebon** [comment]
Hi,
Still not working (I already had built poco when I sent the first message).

**Comment by sindharta** [comment]
The build script is looking for Poco library files, such as 
- `PocoFoundationmd.lib`
- `PocoUtilmd.lib`
etc

Do you have these files after building Poco ?

For debugging, perhaps you can take a look at 
[`MeshSyncDCCPlugin\Plugins~\Build\cmake_modules\FindPoco.cmake`](https://github.com/Unity-Technologies/MeshSyncDCCPlugins/blob/dev/Plugins~/Build/cmake_modules/FindPoco.cmake)
and put debug messages there to find out which file is missing.

Deleting `CMakeCache.txt` is also one thing to try, since it ensures that everything is rebuilt from scratch instead of using the previous build results.

**Comment by sindharta** [comment]
Closing due to no response.
Feel free to reopen if necessary.
