### ISSUE TITLE
add 3ds Max 2022, 2023 SDK and future versions compatibility

### ISSUE THREAD

**Issue by FrogsInSpace** [Unity-Technologies/MeshSyncDCCPlugin#184]
I added 3ds Max 2022, 2023 and possible future versions compatibility to my fork of the MeshSyncDCCPlugins
i also added some  filtering code to the CMakeList to only create the build folders for actually installed 3ds Max SDKs
As this is the first time i try to contribute to the upstream of a public github repo, i'm not exactly sure how and where to procede from that.  I know i should create a pull request, but first i wanted to be sure that this is even a wanted contribution .

Any more head ups would be welcome .. thanks!

**Comment by sindharta** [comment]
> wanted to be sure that this is even a wanted contribution

Yes ! Thank you in advance.
Please make a PR so that we can take a look first.

**Comment by FrogsInSpace** [comment]
Awsome ! ... PR is ready :)

**Comment by sindharta** [comment]
Thank you very much. 
Looks good, but please wait a bit for the merge.

**Comment by FrogsInSpace** [comment]
sure - no problem

**Comment by sindharta** [comment]
Merged to dev branch.
https://github.com/Unity-Technologies/MeshSyncDCCPlugins/pull/190

Thank you very much for your contribution !
