### ISSUE TITLE
Blender MeshSync DDC "Failed to Install" - It was installed but not detected.

### ISSUE THREAD

**Issue by SimonNordon4** [Unity-Technologies/MeshSyncDCCPlugin#194]
![image](https://user-images.githubusercontent.com/86404984/167275609-e32a453b-2831-4ed5-a88e-2e72ffd427a0.png)

![image](https://user-images.githubusercontent.com/86404984/167275626-a22caaaf-642a-4767-876a-383433ee7a5b.png)

Mesh sync auto-installation said it "failed to install" the plugin, only it did install. However no Sync can be established.

**Comment by sindharta** [comment]
That is unexpected. 
Is there any error log in the Console window after the auto-installation ?

**Comment by sindharta** [comment]
Closing due to non-activity. 
Please reopen again if this problem still persists.
