### ISSUE TITLE
Support for adding custom python code to run during the sync process

### ISSUE THREAD

**Issue by erik-sutton95** [Unity-Technologies/MeshSyncDCCPlugin#201]
Hi!

More of a question. Would it be possible or is it currently possible to run custom python code during the sync process? Similarly to how the "Bake Transform" or "Apply Modifiers" works, but with custom python. I'm trying to convert attributes created within a geometry node to a UV set so that the generated mesh can be properly used in Unity.

**Comment by sindharta** [comment]
Hi, and sorry for the late reply.
It's currently not possible to run custom python code.
We are currently working on something similar, although it's still too early to tell when/if we are going to release it.
Stay tuned !

**Comment by schinkowski** [comment]
Thank you for feedback @Esindesign.
In version 0.16 we added event lists that you can append your methods to, which should allow you to do what you want.
These are called mesh_sync_on_prepare, mesh_sync_on_pre_export and mesh_sync_on_post_export.

**Comment by sindharta** [comment]
Closing.
Feel free to reopen if necessary.
