### ISSUE TITLE
Why supports only Standalone Build?

### ISSUE THREAD

**Issue by wewrere41** [Unity-Technologies/MeshSyncDCCPlugin#226]
We are developing android games. And we would like to use mesh sync. Will Android build support come?

**Comment by sindharta** [comment]
For runtime builds in Android ?
It's not in our roadmap for now.

FYI, this is a duplicate of 
https://github.com/unity3d-jp/MeshSync/issues/110

**Comment by wewrere41** [comment]
> For runtime builds in Android ? It's not in our roadmap for now.
> 
> FYI, this is a duplicate of [unity3d-jp/MeshSync#110](https://github.com/unity3d-jp/MeshSync/issues/110)

No runtime. I mean target build platform . Its can't works when I change target platform to android.
