### ISSUE TITLE
Installed the MeshSync in unity(verson 2021.3.6f1c1 lts), but can not find the UI in toolbar

### ISSUE THREAD

**Issue by whitezq** [Unity-Technologies/MeshSyncDCCPlugin#245]

**Comment by sindharta** [comment]
Can you clarify: 
* What UI are you expecting to see ?
* Which toolbar are you referring to ?
* What are you trying to do ?

**Comment by sindharta** [comment]
Closing due to non-activity.
Please reopen if the issue still persists.
