### ISSUE TITLE
Syncing lights spawned by Blender GN

### ISSUE THREAD

**Issue by bitinn** [Unity-Technologies/MeshSyncDCCPlugin#253]
It looks like syncing non-mesh object created by Blender Geometry nodes are not currently possible.

A possible use case is using GN to spawn a bunch of light instances, MeshSync doesn't appear to handle that as of 3.2.2

**Comment by sindharta** [comment]
Thank you for the feedback. 
We'll take a look at this.

**Comment by schinkowski** [comment]
Thank you for your feedback @bitinn. This should work in Version 0.16.

**Comment by sindharta** [comment]
Closing.
Feel free to reopen if necessary.
