### ISSUE TITLE
How can i get texture sync from Blender in Unity?

### ISSUE THREAD

**Issue by ShockWave2048** [Unity-Technologies/MeshSyncDCCPlugin#262]
How can i get texture sync from Blender in Unity?
Blender 3.2/Unity 2022.1.15f1

**Comment by sindharta** [comment]
The name of the materials will be synced, but we need to do the texture assignments manually for now.

In other words, we can't directly sync textures from Blender to Unity yet.

**Comment by schinkowski** [comment]
Thank you for your feedback @ShockWave2048 .
In version 0.16 you can choose a material sync mode to transfer material settings and textures. To make the materials work with the default shaders in Unity, we can only sync textures and values directly connected to the BSDF, not procedural materials. 
This is the initial implementation, feedback is very welcome.

**Comment by sindharta** [comment]
Please feel free to reopen if necessary.
