### ISSUE TITLE
Blender Plugin doesn't seem to work

### ISSUE THREAD

**Issue by AndreyZhukov** [Unity-Technologies/MeshSyncDCCPlugin#37]
Hi, I tried to install the Blender plugin of MeshSync on version 2.81 and 2.82a and it doesn't work I guess. Should I see the object at least in the browser under 127.0.0.1:8080? Or if there's a Unity problem, browser won't display it (the object from Blender) (because Unity hosts/creates the server?)?
Andrey

**Comment by sindharta** [comment]
Are you referring to the browser feature or the connection between Unity and Blender in general ?
You should be able to sync the object in Unity and Blender.
Can you post screenshots showing that it doesn't work ?

**Comment by sindharta** [comment]
Closing due to non-activity. Please feel free to reopen this if you still have the problem
