### ISSUE TITLE
Plugin .zip downloads removed???

### ISSUE THREAD

**Issue by mr-brooks-dev** [Unity-Technologies/MeshSyncDCCPlugin#43]
Hi. 
In your docmentation for setting up MeshSync for Maya, you link to the releases section to download the Maya plugin.
I dont see DCC plugins downloadable in the releases section.

This suprises me because I thought I had downloaded the Maya plugin from here belore???
Please help.

**Comment by sindharta** [comment]
I apologize for the late reply.
The DCC plugins can be located in the [releases](https://github.com/Unity-Technologies/MeshSyncDCCPlugins/releases) section.
I am not sure why you can't see them.

You may also want to try the new "[DCC Tools setting](https://docs.unity3d.com/Packages/com.unity.meshsync@0.2/manual/en/ProjectSettings.html#dcc-tools)"  in MeshSync package, which will try to download and install the supported DCC Plugin automatically.

**Comment by sindharta** [comment]
Closing issue due to non-activity.
Please feel free to contact us again if you still have this issue.
