### ISSUE TITLE
Roadmap: DCC Tools Support 

### ISSUE THREAD

**Issue by sindharta** [Unity-Technologies/MeshSyncDCCPlugin#7]
### Possibly be done in the future
- [ ] Houdini
- [ ] Cinema 4D
- [ ] Photoshop (texture and screen painting)

### Done
- [x] Modo
- [x] VRED
- [x] Motion Builder
- [x] 3ds Max
- [x] Maya
- [x] Blender
- [x] xismo
- [x] Metasequoia

### Gave up
- [x] ZBrush
  - no plugin API and it's software rendering (= impossible to snoop vertices)

**Comment by sindharta** [comment]
No plan for other DCC tools at this moment.

**Comment by Nolram12345** [comment]
Houdini support would be amazing for working on simulations that integrate with the game world.
