### ISSUE TITLE
RizomUV pipeline ??

### ISSUE THREAD

**Issue by davoodkharmanzar** [Unity-Technologies/MeshSyncDCCPlugin#97]
it would be great if be able to transfer selected scene object mesh from unity to [RizomUV  ](https://www.rizom-lab.com/rizomuv-vs/) to build primary uv or lightmapping uv  :]

something like as RizomUV [bridges ](https://www.rizom-lab.com/bridges/)...

thanks a lot.

**Comment by sindharta** [comment]
Thank you for your interest in using MeshSync.
I am not familiar with RizomUV yet, but unfortunately MeshSync is designed to transfer data from DCC tool side to Unity, and not the other way around.
For transferring data from Unity to DCC tools, you can use [FBXExporter](https://docs.unity3d.com/Packages/com.unity.formats.fbx@latest)

**Comment by sindharta** [comment]
Closing due to non-activity.
